---
zabbix_agent_server_address: node3.example.com
zabbix_agent_server_active_address: node3.example.com

users_group_list:
  - name: robertdb

users_user_list:
  - name: robertdb
    comment: Robert de Bock
    group: robertdb
    groups: wheel
    cron_allow: yes
    sudo_options: "ALL=(ALL) NOPASSWD: ALL"
    password: "$1$QbmM32Kz$nzFTRRxti0ZZ2oSC6ii8p1"
    authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCWswOogkZz/ihQA0lENCwDwSzmtmBWtFwzIzDlfa+eb4rBt6rZBg7enKeMqYtStI/NDneBwZUFBDIMu5zJTbvg7A60/WDhWXZmU21tZnm8K7KREFYOUndc6h//QHig6IIaIwwBZHF1NgXLtZ0qrUUlNU5JSEhDJsObMlPHtE4vFP8twPnfc7hxAnYma5+knU6qTMCDvhBE5tGJdor4UGeAhu+SwSVDloYtt1vGTmnFn8M/OD/fRMksusPefxyshJ37jpB4jY/Z9vzaNHwcj33prwl1b/xRfxr/+KRJsyq+ZKs9u2TVw9g4p+XLdfDtzZ8thR2P3x3MFrZOdFmCbo/5"
